name: Release

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'platform'
        required: true
        default: 'warning'
        type: choice
        options:
          - win-32
          - win-64
          - mac
          - linux

jobs:
  build:
    runs-on: ubuntu-latest
    if: "ithub.event.inputs.platform == 'linux'"
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Free up some disk space on ubuntu
      if: ${{ runner.os == 'Linux' }}
      run: |
        # Workaround to provide additional free space for testing.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
        check-latest: true

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --timeout 120m
      run: |
        ls
        cd dist
        lad
